name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ACTIONS_STEP_DEBUG: true

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write
      issues: write
      actions: read      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: AI Code Review
        uses: anetrebskii/agentic-review@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}          